interface StaticDashboardTemplateContent {
  staticLede: string;
  staticButtonLabel: string;
  staticTrendTitle: string;
  staticTrendBadge: string;
  staticActivityTitle: string;
  staticActivityBadge: string;
  staticStats: Array<{ label: string; value: string | number; delta: string }>;
  staticTrend: number[];
  staticActivity: string[];
}

interface StaticCrudTemplateContent {
  lede: string;
  singularLabel: string;
  pluralLabel: string;
  nameLabel: string;
  namePlaceholder: string;
  ownerLabel: string;
  ownerPlaceholder: string;
  searchLabel: string;
  initialRecords: Array<Record<string, string>>;
}

export function buildStaticDashboardHtmlTemplate(title: string, content: StaticDashboardTemplateContent): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title}</title>
    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
    <main class="dashboard-shell">
      <section class="dashboard-hero">
        <div>
          <p class="eyebrow">Generated by Cipher Workspace</p>
          <h1>${title}</h1>
          <p class="lede">${content.staticLede}</p>
        </div>
        <button id="refresh-dashboard" type="button">${content.staticButtonLabel}</button>
      </section>

      <section class="stats-grid" id="stats-grid"></section>

      <section class="dashboard-grid">
        <article class="panel">
          <div class="panel-head">
            <h2>${content.staticTrendTitle}</h2>
            <span id="trend-badge">${content.staticTrendBadge}</span>
          </div>
          <div class="bars" id="trend-bars"></div>
        </article>
        <article class="panel">
          <div class="panel-head">
            <h2>${content.staticActivityTitle}</h2>
            <span>${content.staticActivityBadge}</span>
          </div>
          <div id="activity-list" class="activity-list"></div>
        </article>
      </section>
    </main>
    <script src="app.js"></script>
  </body>
</html>
`;
}

export function buildStaticDashboardJsTemplate(content: StaticDashboardTemplateContent): string {
  return `const stats = ${JSON.stringify(content.staticStats, null, 2)};

const trend = ${JSON.stringify(content.staticTrend)};
const activity = ${JSON.stringify(content.staticActivity, null, 2)};

function renderDashboard() {
  const statsGrid = document.getElementById("stats-grid");
  const trendBars = document.getElementById("trend-bars");
  const activityList = document.getElementById("activity-list");
  const badge = document.getElementById("trend-badge");
  if (!statsGrid || !trendBars || !activityList || !badge) return;

  statsGrid.innerHTML = stats.map((item) => '<article class="stat-card"><span>' + item.label + '</span><strong>' + item.value + '</strong><span>' + item.delta + ' vs last cycle</span></article>').join("");
  trendBars.innerHTML = trend.map((value) => '<div class="bar" style="height:' + value + 'px"></div>').join("");
  activityList.innerHTML = activity.map((item, index) => '<article class="activity-item"><strong>Update ' + (index + 1) + '</strong><p>' + item + '</p></article>').join("");
  badge.textContent = trend[trend.length - 1] >= trend[0] ? "Upward" : "Watch";
}

document.getElementById("refresh-dashboard")?.addEventListener("click", () => {
  trend.push(trend.shift());
  renderDashboard();
});

renderDashboard();
`;
}

export function buildStaticCrudHtmlTemplate(
  title: string,
  content: StaticCrudTemplateContent,
  singularDisplayLabel: string,
  pluralDisplayLabel: string
): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title}</title>
    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
    <main class="crud-shell">
      <section class="crud-hero">
        <div>
          <p class="eyebrow">Generated by Cipher Workspace</p>
          <h1>${title}</h1>
          <p class="lede">${content.lede}</p>
        </div>
      </section>

      <section class="crud-grid">
        <form class="panel form-panel" id="record-form">
          <div class="panel-head">
            <h2>${singularDisplayLabel} details</h2>
            <span id="form-mode">Create</span>
          </div>
          <label>${content.nameLabel}<input id="record-name" placeholder="${content.namePlaceholder}" /></label>
          <label>Status
            <select id="record-status">
              <option>Active</option>
              <option>Paused</option>
              <option>Review</option>
            </select>
          </label>
          <label>${content.ownerLabel}<input id="record-owner" placeholder="${content.ownerPlaceholder}" /></label>
          <button type="submit">Save ${content.singularLabel}</button>
        </form>

        <section class="panel table-panel">
          <div class="panel-head">
            <div>
              <h2>${pluralDisplayLabel}</h2>
              <span id="records-count">0 ${content.pluralLabel}</span>
            </div>
            <label class="search-field">${content.searchLabel}<input id="record-search" placeholder="Search ${content.pluralLabel}..." /></label>
          </div>
          <div id="records-list" class="records-list"></div>
        </section>
      </section>
    </main>
    <script src="app.js"></script>
  </body>
</html>
`;
}

export function buildStaticCrudJsTemplate(content: StaticCrudTemplateContent): string {
  return `const state = {
  editingId: "",
  records: ${JSON.stringify(content.initialRecords, null, 2)}
};

const formEl = document.getElementById("record-form");
const nameEl = document.getElementById("record-name");
const statusEl = document.getElementById("record-status");
const ownerEl = document.getElementById("record-owner");
const listEl = document.getElementById("records-list");
const countEl = document.getElementById("records-count");
const modeEl = document.getElementById("form-mode");
const searchEl = document.getElementById("record-search");

function resetForm() {
  state.editingId = "";
  if (nameEl) nameEl.value = "";
  if (statusEl) statusEl.value = "Active";
  if (ownerEl) ownerEl.value = "";
  if (modeEl) modeEl.textContent = "Create";
}

function startEdit(id) {
  const record = state.records.find((item) => item.id === id);
  if (!record || !nameEl || !statusEl || !ownerEl || !modeEl) return;
  state.editingId = id;
  nameEl.value = record.name;
  statusEl.value = record.status;
  ownerEl.value = record.owner;
  modeEl.textContent = "Edit";
}

function renderRecords() {
  if (!listEl || !countEl || !searchEl) return;
  const query = String(searchEl.value || "").trim().toLowerCase();
  const visible = state.records.filter((record) => {
    if (!query) return true;
    return [record.name, record.status, record.owner].some((value) => value.toLowerCase().includes(query));
  });

  countEl.textContent = visible.length + (visible.length === 1 ? " record" : " records");
  if (visible.length === 0) {
    listEl.innerHTML = '<article class="record-item"><h3>No matches</h3><p>Try a different search term or save a new ${content.singularLabel}.</p></article>';
    return;
  }

  listEl.innerHTML = visible.map((record) => '<article class="record-item"><div class="record-top"><div><h3>' + record.name + '</h3><div class="record-meta"><span class="badge">' + record.status + '</span><span class="badge">' + record.owner + '</span></div></div></div><div class="actions"><button class="ghost" type="button" data-record-edit="' + record.id + '">Edit</button><button class="ghost" type="button" data-record-delete="' + record.id + '">Delete</button></div></article>').join("");

  listEl.querySelectorAll("[data-record-edit]").forEach((button) => {
    button.addEventListener("click", () => startEdit(button.getAttribute("data-record-edit") || ""));
  });
  listEl.querySelectorAll("[data-record-delete]").forEach((button) => {
    button.addEventListener("click", () => {
      const id = button.getAttribute("data-record-delete");
      state.records = state.records.filter((record) => record.id !== id);
      if (state.editingId === id) resetForm();
      renderRecords();
    });
  });
}

formEl?.addEventListener("submit", (event) => {
  event.preventDefault();
  const name = String(nameEl?.value || "").trim();
  const status = String(statusEl?.value || "").trim();
  const owner = String(ownerEl?.value || "").trim();
  if (!name || !status || !owner) return;

  if (state.editingId) {
    state.records = state.records.map((record) => record.id === state.editingId ? { ...record, name, status, owner } : record);
  } else {
    state.records.unshift({ id: String(Date.now()), name, status, owner });
  }

  resetForm();
  renderRecords();
});

searchEl?.addEventListener("input", renderRecords);
resetForm();
renderRecords();
`;
}
